<?php

return [
    'editable' => [
        'marketplace_ebay' => [
            'label' => 'eBay',
            'description' => 'OAuth app credentials, marketplace defaults, and Sell API scopes for the eBay adapter.',
            'help_title' => 'How to configure eBay OAuth',
            'help_intro' => 'You will switch between Belimbing and the eBay Developer Console. First copy the app keys into Belimbing, then open eBay’s <code>User Tokens</code> page to configure the sign-in callback and copy back the generated <code>RuName</code>.',
            'help_steps' => [
                [
                    'before_link' => 'Open the ',
                    'link_label' => 'eBay Developer Console',
                    'url' => 'https://developer.ebay.com/my/keys',
                    'after_link' => ', then choose the matching Sandbox or Production app keyset.',
                ],
                'Copy the app Keyset <code>App ID</code> into Belimbing’s <code>App ID (Client ID)</code> field, and copy <code>Cert ID</code> into Belimbing’s <code>Cert ID (Client secret)</code> field. Use the <code>Sandbox</code> keyset when Environment is <code>Sandbox</code>, and the <code>Production</code> keyset when Environment is <code>Live</code>.',
                'Click <code>User Tokens</code> next to that keyset’s <code>App ID</code>, then create or select the <code>Redirect URL name (RuName)</code> for that environment. If eBay says there are no Redirect URLs, follow its prompt to add one first.',
                'Set <code>Display Title</code> to <code>Belimbing</code> so the eBay consent page names the app clearly.',
                'Enter a public HTTPS <code>Privacy Policy URL</code>. eBay requires this for User access tokens because Belimbing will read seller account, listing, and order data. The upstream project policy is <code>https://github.com/belimbingapp/belimbing/blob/main/PRIVACY.md</code>; production installations should publish their own policy if their data practices differ.',
                'Copy the <code>Belimbing Callback URL</code> from this page into both eBay’s <code>Auth Accepted URL</code> and <code>Auth Declined URL</code> fields. Belimbing owns the callback and will show the right success or declined result.',
                'Select <code>OAuth</code>, not <code>Auth’n’Auth</code>, then save the eBay sign-in settings.',
                'Copy the generated <code>RuName</code> back into Belimbing’s <code>Redirect URL name</code> field, save settings, click <code>Connect eBay</code>, approve the requested scopes, then run <code>Test connection</code>.',
            ],
            'fields' => [
                [
                    'key' => 'marketplace.ebay.environment',
                    'label' => 'Environment',
                    'type' => 'select',
                    'scope' => 'company',
                    'default' => 'sandbox',
                    'options' => ['sandbox' => 'Sandbox', 'live' => 'Live'],
                    'help' => 'Sandbox: test API with sandbox keys. Live: real eBay account with production keys.',
                    'rules' => ['required', 'in:sandbox,live'],
                ],
                [
                    'key' => 'marketplace.ebay.marketplace_id',
                    'label' => 'Marketplace ID',
                    'type' => 'select',
                    'scope' => 'company',
                    'default' => 'EBAY_US',
                    'options' => [
                        'EBAY_US' => 'United States (EBAY_US)',
                        'EBAY_GB' => 'United Kingdom (EBAY_GB)',
                        'EBAY_AU' => 'Australia (EBAY_AU)',
                        'EBAY_CA' => 'Canada (EBAY_CA)',
                        'EBAY_DE' => 'Germany (EBAY_DE)',
                        'EBAY_FR' => 'France (EBAY_FR)',
                        'EBAY_IT' => 'Italy (EBAY_IT)',
                        'EBAY_ES' => 'Spain (EBAY_ES)',
                        'EBAY_NL' => 'Netherlands (EBAY_NL)',
                        'EBAY_BE' => 'Belgium (EBAY_BE)',
                        'EBAY_AT' => 'Austria (EBAY_AT)',
                        'EBAY_CH' => 'Switzerland (EBAY_CH)',
                        'EBAY_IE' => 'Ireland (EBAY_IE)',
                        'EBAY_PL' => 'Poland (EBAY_PL)',
                        'EBAY_HK' => 'Hong Kong (EBAY_HK)',
                        'EBAY_SG' => 'Singapore (EBAY_SG)',
                        'EBAY_MY' => 'Malaysia (EBAY_MY)',
                        'EBAY_PH' => 'Philippines (EBAY_PH)',
                        'EBAY_MOTORS' => 'eBay Motors (EBAY_MOTORS)',
                    ],
                    'help' => 'The eBay site where this company sells. Choose the country/site from the list.',
                    'rules' => ['required', 'string', 'max:32'],
                    'normalize' => 'uppercase',
                ],
                [
                    'key' => 'marketplace.ebay.client_id',
                    'label' => 'App ID (Client ID)',
                    'type' => 'text',
                    'scope' => 'company',
                    'placeholder' => 'App ID from eBay Developer Console',
                    'help' => 'Paste App ID from the matching Sandbox or Production keyset in the eBay Developer Console.',
                    'rules' => ['nullable', 'string', 'max:255'],
                ],
                [
                    'key' => 'marketplace.ebay.client_secret',
                    'label' => 'Cert ID (Client secret)',
                    'type' => 'password',
                    'scope' => 'company',
                    'encrypted' => true,
                    'help' => 'Paste Cert ID from the same eBay keyset. Focus to replace; saving without changes keeps the saved secret.',
                    'rules' => ['nullable', 'string', 'max:500'],
                ],
                [
                    'key' => 'marketplace.ebay.ru_name',
                    'label' => 'Redirect URL name (RuName)',
                    'type' => 'text',
                    'scope' => 'company',
                    'placeholder' => 'Your_App-YourApp-SBX-abcde',
                    'help' => 'Paste the RuName from eBay User Tokens. It usually looks like Your_App-YourApp-SBX-abcde.',
                    'rules' => ['nullable', 'string', 'max:255'],
                ],
                [
                    'key' => 'marketplace.ebay.callback_url',
                    'label' => 'Belimbing Callback URL',
                    'type' => 'readonly',
                    'value_route' => 'commerce.marketplace.ebay.oauth.callback',
                    'help' => 'Copy this URL into both Auth Accepted URL and Auth Declined URL for the eBay RuName.',
                ],
                [
                    'key' => 'marketplace.ebay.scopes',
                    'label' => 'OAuth scopes',
                    'type' => 'checkbox-list',
                    'advanced' => true,
                    'advanced_label' => 'Advanced OAuth settings',
                    'advanced_help' => 'Belimbing selects the scopes needed for eBay sync and setup. Change only for debugging or read-only testing.',
                    'scope' => 'company',
                    'default' => [
                        'https://api.ebay.com/oauth/api_scope/sell.inventory',
                        'https://api.ebay.com/oauth/api_scope/sell.account',
                        'https://api.ebay.com/oauth/api_scope/sell.fulfillment',
                    ],
                    'help' => 'Seller permissions shown on eBay consent. Defaults support listings, orders, seller setup, and future publishing.',
                    'options' => [
                        'https://api.ebay.com/oauth/api_scope/sell.inventory' => [
                            'label' => 'Sell Inventory',
                            'help' => 'Inventory items, offers, listing publication, and listing state.',
                        ],
                        'https://api.ebay.com/oauth/api_scope/sell.account' => [
                            'label' => 'Sell Account',
                            'help' => 'Seller account setup used by offers, including business policies and inventory locations.',
                        ],
                        'https://api.ebay.com/oauth/api_scope/sell.fulfillment' => [
                            'label' => 'Sell Fulfillment',
                            'help' => 'Order fulfillment data for sales reconciliation and marking inventory sold.',
                        ],
                    ],
                    'rules' => ['required', 'array', 'min:1'],
                ],
            ],
        ],
    ],
];
